project:
  type: website
  output-dir: docs

website:
  title: "Charadrius & Coccothraustes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Grosbeaks.qmd
      - Plovers.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



